using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Mirath.Infrastructure.Migrations
{
    public partial class AddLegacySupportTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "SubscriptionPlans" (
    "Id" uuid PRIMARY KEY,
    "Name" character varying(100) NOT NULL,
    "PlanType" integer NOT NULL UNIQUE,
    "MonthlyPrice" numeric(18,2) NOT NULL,
    "MonthlyCaseLimit" integer NOT NULL,
    "HasAdvancedCalculator" boolean NOT NULL,
    "HasPdfExports" boolean NOT NULL,
    "HasPrioritySupport" boolean NOT NULL,
    "HasClientManagement" boolean NOT NULL,
    "HasAdminAccess" boolean NOT NULL,
    "IsSystemPlan" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "UserSubscriptions" (
    "Id" uuid PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "PlanId" uuid NOT NULL REFERENCES "SubscriptionPlans"("Id") ON DELETE RESTRICT,
    "Status" integer NOT NULL,
    "CasesUsedThisPeriod" integer NOT NULL,
    "UsagePeriodStart" timestamp with time zone NOT NULL,
    "UsagePeriodEnd" timestamp with time zone NOT NULL,
    "StartsAt" timestamp with time zone NOT NULL,
    "EndsAt" timestamp with time zone NULL,
    "AutoRenew" boolean NOT NULL,
    "Currency" character varying(8) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL
);
CREATE INDEX IF NOT EXISTS "IX_UserSubscriptions_UserId_Status" ON "UserSubscriptions" ("UserId", "Status");

CREATE TABLE IF NOT EXISTS "Debts" (
    "Id" uuid PRIMARY KEY,
    "CaseId" uuid NOT NULL REFERENCES "Cases"("Id") ON DELETE CASCADE,
    "CreditorName" text NOT NULL,
    "Amount" numeric NOT NULL,
    "Currency" text NOT NULL,
    "Description" text NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_Debts_CaseId" ON "Debts" ("CaseId");

CREATE TABLE IF NOT EXISTS "Calculations" (
    "Id" uuid PRIMARY KEY,
    "CaseId" uuid NOT NULL REFERENCES "Cases"("Id") ON DELETE CASCADE,
    "Madhab" integer NOT NULL,
    "NetEstate" numeric NOT NULL,
    "CalculatedAt" timestamp with time zone NOT NULL,
    "IsAwlApplied" boolean NOT NULL,
    "IsRaddApplied" boolean NOT NULL,
    "TotalSharesRatio" double precision NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_Calculations_CaseId" ON "Calculations" ("CaseId");

CREATE TABLE IF NOT EXISTS "HeirShares" (
    "Id" uuid PRIMARY KEY,
    "CalculationId" uuid NOT NULL REFERENCES "Calculations"("Id") ON DELETE CASCADE,
    "HeirType" integer NOT NULL,
    "HeirName" text NOT NULL,
    "FractionNumerator" double precision NOT NULL,
    "FractionDenominator" double precision NOT NULL,
    "Percentage" double precision NOT NULL,
    "Amount" numeric NOT NULL,
    "ShareType" text NOT NULL,
    "Explanation" text NULL
);
CREATE INDEX IF NOT EXISTS "IX_HeirShares_CalculationId" ON "HeirShares" ("CalculationId");

CREATE TABLE IF NOT EXISTS "CalculationSteps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StepName" text NOT NULL,
    "Description" text NOT NULL,
    "InitialValue" double precision NULL,
    "FinalValue" double precision NULL
);

CREATE TABLE IF NOT EXISTS "ChatHistories" (
    "Id" uuid PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "CaseId" uuid NULL,
    "Role" character varying(20) NOT NULL,
    "Content" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS "IX_ChatHistories_UserId" ON "ChatHistories" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_ChatHistories_CaseId" ON "ChatHistories" ("CaseId");
CREATE INDEX IF NOT EXISTS "IX_ChatHistories_Timestamp" ON "ChatHistories" ("Timestamp");
""");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS "ChatHistories";
DROP TABLE IF EXISTS "CalculationSteps";
DROP TABLE IF EXISTS "HeirShares";
DROP TABLE IF EXISTS "Calculations";
DROP TABLE IF EXISTS "Debts";
DROP TABLE IF EXISTS "UserSubscriptions";
DROP TABLE IF EXISTS "SubscriptionPlans";
""");
        }
    }
}
